kind: pipeline
type: docker
name: NETWORK CI/CD


steps:
- name: Black Code Format Check
  image: chikamalu/netcicd:latest
  commands:
  - black . --check
- name: Install and deploy docker image
  image: chikamalu/netcicd:latest
  environment:
    PASSWORD:
      from_secret: PASSWORD
    USERNAME:
      from_secret: USERNAME
  commands:
  # - pip3 install -r requirements.txt
  - python3 get_interfaces.py

trigger:
  branch:
    include:
    - main
    - master